version: '3'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"

  scrapy:
    build:
      dockerfile: scrapy.Dockerfile
      context: .
    container_name: scrapy
    ports:
      - "9000:9000"
    links:
      - mongo

  app:
    container_name: app
    build: 
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5000:5000"
    links:
      - mongo
      - elastic
    depends_on: 
      - scrapy
  
